### ISSUE TITLE
Unable to build current osm file

### ISSUE THREAD

**Issue by Trinity-SYT-SECURITY** [lcodeca/SUMOActivityGen#48]
After I created the osm file through www.openstreetmap.org, the execution command failed to create it successfully, and the directory was confirmed to be correct

```
python3 scenarioFromOSM.py --osm map.osm --out test
Namespace(osm_file='map.osm', out_dir='test', left_hand_traffic=False, population=1000, taxi_fleet=10, density=3000.0, single_taz=False, admin_level=None, max_entrance=1000.0, html_filename='', processes=1, from_step=0, to_step=12, profiling=False, gui=False, local_defaults=False)                                                                                                 
Copying default configuration files to destination.                                                                                                                                          
Generate the net.xml with all the additional components (public transports, parkings, ..)                                                                                                    
Loading configuration...                                                                                                                                                                     
Error: No option with the name 'no-turnarounds.except-turnlane' exists.                                                                                                                      
Error: No option with the name 'no-turnarounds.fringe' exists.                                                                                                                               
Error: No option with the name 'junctions.join-same' exists.                                                                                                                                 
Error: No option with the name 'walkingareas.join-dist' exists.                                                                                                                              
Error: No option with the name 'bikelanes.guess' exists.                                                                                                                                     
Error: No option with the name 'bikelanes.guess.min-speed' exists.                                                                                                                           
Error: No option with the name 'bikelanes.guess.max-speed' exists.                                                                                                                           
Error: No option with the name 'bikelanes.guess.from-permissions' exists.                                                                                                                    
Error: No option with the name 'railway.topology.repair.stop-turn' exists.                                                                                                                   
Error: No option with the name 'railway.topology.direction-priority' exists.                                                                                                                 
Error: Could not load configuration 'osm.netccfg'.                                                                                                                                           
Quitting (on error).                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                           
  File "/home/xxx/xxxx/veins-f2md/f2md-networks/securecomm2018/SUMOActivityGen/scenarioFromOSM.py", line 671, in <module>                                                            
    main(sys.argv[1:])                                                                                                                                                                       
  File "/home/xxx/xxxx/veins-f2md/f2md-networks/securecomm2018/SUMOActivityGen/scenarioFromOSM.py", line 586, in main                                                                
    _call_netconvert(args.osm_file, args.left_hand_traffic)                                                                                                                                  
  File "/home/xxx/xxxx/veins-f2md/f2md-networks/securecomm2018/SUMOActivityGen/scenarioFromOSM.py", line 270, in _call_netconvert                                                    
    subprocess.check_call(netconvert_options)                                                                                                                                                
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call                                                                                                                          
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['netconvert', '-c', 'osm.netccfg', '--osm', 'map.osm', '-o', 'osm.net.xml', '--ptstop-output', 'osm_stops.add.xml', '--ptline-output', 'osm_ptlines.xml', '--parking-output', 'osm_parking.xml', '--type-files', '/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvert.typ.xml,/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvertBicycle.typ.xml,/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvertPedestrians.typ.xml']' returned non-zero exit status 1.

```

**Comment by lcodeca** [comment]
The last line that you posted contains exactly the command line that is used for netconvert.
```
netconvert -c osm.netccfg --osm map.osm -o osm.net.xml --ptstop-output osm_stops.add.xml --ptline-output osm_ptlines.xml --parking-output osm_parking.xml --type-files '/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvert.typ.xml,/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvertBicycle.typ.xml,/home/xxx/Programs/sumo-1.2.0/data/typemap/osmNetconvertPedestrians.typ.xml
```
Have you tried it? if so, what's the error?
Based on the error, it's possible that you'll have to ask the SUMO community, cause SAGA here is just using netconvert :)

**Comment by Trinity-SYT-SECURITY** [comment]
When I try this command, he also gives me an error

```
Error: Could not access configuration 'osm.netccfg'.
Quitting (on error).
```

**Comment by lcodeca** [comment]
I don't know how you call any of the commands, and what is your directory structure.
This is not an error from SAGA, it tells you it cannot find the file.
